// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Operative.Api.Infrastructure.Persistence;

#nullable disable

namespace Operative.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OperativeDbContext))]
    [Migration("20261006195002_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Operative.Api.Domain.Entities.DiceRoll", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Die1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Die2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sum")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAtUtc")
                        .HasDatabaseName("IX_DiceRolls_UserId_CreatedAtUtc");

                    b.HasIndex("UserId", "Sum")
                        .HasDatabaseName("IX_DiceRolls_UserId_Sum");

                    b.ToTable("DiceRolls", null, t =>
                        {
                            t.HasCheckConstraint("CK_DiceRolls_Die1_Range", "\"Die1\" BETWEEN 1 AND 6");

                            t.HasCheckConstraint("CK_DiceRolls_Die2_Range", "\"Die2\" BETWEEN 1 AND 6");

                            t.HasCheckConstraint("CK_DiceRolls_Sum", "\"Sum\" = \"Die1\" + \"Die2\"");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
